### ISSUE TITLE
The lack of proper documentation makes this library completely unusable

### ISSUE THREAD

**Issue by tim-hardcastle** [tliron/glsp#18]
Maybe it would make sense to someone who's done a lot of other language parsers using a lot of other libraries. It's completely useless to a beginner. "All you need to do, then, is provide the features for the language you want to support", it says, in one of the ten lines of documentation. It doesn't hint at how.

I would give my back teeth for a simple demo that put red wiggly lines under the word `foo` in any file with extension `.bar`, I could take it from there. I'm going to use the first library I can find which has such an example, except I'm starting to doubt there is one. It seems like everyone who's ever spent months of effort writing an LSP library in Go has then decided to ensure that all their effort will be wasted and useless by not spending another half-an-hour on writing any docs.

**Comment by tliron** [comment]
"Thank you" for your awful comment. People like you are why many of us in open source get burnt out and stop participating.

I will ignore your shitty attitude and answer the actual comment, pretending it was a question. Why is there no in-depth documentation? Because teaching LSP is a book-length endeavor. There's nothing special about this particular implementation, except that it's in Go and more comprehensive and up-to-date than others.

Maybe one day you will understand that open source is a volunteer, communal effort. Contributions of example parsers and more documentation are very welcome here, but I doubt I will ever get a contribution from you. People like think they are entitled to something from people like me. Take your back teeth and wiggly lines elsewhere, please.

**Comment by mickael-menu** [comment]
In my experience, Tal was very helpful and responsive with questions. Yes glsp lacks documentation, but it's a one-man open source project. The fact that it is still maintained three years in is already a miracle compared to most similar projects.

Once you get through [the configuration phase](https://github.com/tliron/glsp/issues/6), it's very straightforward and a matter of reading [the official LSP specification](https://microsoft.github.io/language-server-protocol/).

I hope you take a step back and realize how entitled you sound, and come back to apologize.

**Comment by tliron** [comment]
Thanks @mickael-menu! Actually, glsp has progressed purely because of community contributions. After my initial release I unfortunately had to move on to other projects, however I am hoping to get back some day and add some polish. Documentation is definitely a priority, as is a test harness (there currently is none...). I'm very open to anyone taking it in any direction that makes sense!
